version: '3'

services:
  application:
    container_name: application
    build:
      context: .
    ports:
      - "8080:8080"
    command: uvicorn main:app --host 0.0.0.0 --port 8080 --reload
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
